### ISSUE TITLE
errors when executing below codes.

### ISSUE THREAD

**Issue by dannyng1988** [PacktPublishing/Hands-On-Python-Natural-Language-Processing#1]
`import ast 
questions = []
answers = [] 
with open('qa_Electronics.json','r') as f:
    for line in f:
        data = ast.literal_eval(line)
        questions.append(data['question'].lower())
        answers.append(data['answer'].lower())` 

**File "<unknown>", line 1
    {'questionType': 'yes/no', 'asin': 'B00005T3BD', 'answerTime': 'Apr 8, 2015', 'unixTime': 1428476400, 'quesvoltage (110V-240V) ?', 'answerType': '?', 'answer': 'According to the manual its 120V only'}
                                                                                                                                     ^
SyntaxError: invalid syntax**

**Comment by mayankrasu** [comment]
You are getting this error because the above line of data is incorrect and not of json format. 'quesvoltage (110V-240V) ?' is a standalone string and is not of the format "abc":"xyx which would be consistent with json/python dictionary.

Did you edit the qa_Electronics.json file by any chance? I just checked the original data and this line (line 175609 of the json file) should be the following.

{'questionType': 'yes/no', 'asin': 'B0083IG8K2', 'answerTime': 'Aug 1, 2014', 'unixTime': 1406876400, 'question': 'Is it free voltage (110V-240V) ?', 'answerType': '?', 'answer': 'According to the manual its 120V only'}

**Comment by dannyng1988** [comment]
I didn't edit the json file. I downloaded it from your github repository.

**Comment by mayankrasu** [comment]
I just checked the zip file that is in the repository and it is fine. Can you please download the zip file and extract the json again.

**Comment by dannyng1988** [comment]
it worked. Thank you.
